// JavaScript Document --all states--

var abia = "<span class='normalfontwhite'>Places in Abia</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='abia'>EVERYWHERE</option><option value='aba'>ABA-CENTRAL LOCATIONS</option><option value='ikwuano'>IKWUANO</option><option value='umuahia_central_locations'>UMUAHIA CENTRAL LOCATIONS</option><option value='umudike'>UMUDIKE</option></select>";

var abuja = "<span class='normalfontwhite'>Places in FCT Abuja</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='abuja'>EVERYWHERE</option><option value='abaji'>ABAJI</option><option value='abuja_central_locations'>ABUJA CENTRAL LOCATIONS</option><option value='dei_dei'>DEI DEI</option><option value='gwagwa'>GWAGWA</option><option value='gwagwalada_central_locations'>GWAGWALADA CENTRAL LOCATIONS</option><option value='idu'>IDU</option><option value='karmo'>KARMO</option><option value='karshi'>KARSHI</option><option value='karu' >KARU</option><option value='kuje'>KUJE</option><option value='kwali'>KWALI</option><option value='sheda'>SHEDA</option></select>";		

var adamawa = "<span class='normalfontwhite'>Places in Adamawa</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='adamawa'>EVERYWHERE</option><option value='gombi'>GOMBI</option><option value='hong'>HONG</option><option value='mayo_belwa'>MAYO BELWA</option><option value='mubi'>MUBI</option><option value='ngurore'>NGURORE</option><option value='numan'>NUMAN</option><option value='song'>SONG</option><option value='yola_central_locations'>YOLA CENTRAL LOCATIONS</option></select>";

var akwa_ibom = "<span class='normalfontwhite'>Places in Akwa-ibom</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='akwa-ibom'>EVERYWHERE</option><option value='abak'>abak</option><option value='eket'>EKET</option><option value='eket_central_locations'>EKET CENTRAL LOCATIONS</option><option value='etinan'>ETINAN</option><option value='ikot_abassi'>IKOT ABASSI</option><option value='ikot_ekpene'>IKOT EKPENE</option><option value='ikot_osura'>IKOT OSURA</option><option value='mikpat_enin'>MIKPAT ENIN</option><option value='oron'>ORON</option><option value='qua_iboh_terminal'>QUA IBOH TERMINAL</option><option value='uyo'>UYO</option><option value='uyo_central_locations'>UYO CENTRAL LOCATIONS</option></select>";

var anambra = "<span class='normalfontwhite'>Places in Anambra</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='anambra'>EVERYWHERE</option><option value='achalla'>ACHALLA / AWKA</option><option value='amawbia'>AMAWBIA / AWKA</option><option value='awka_town'>awka town</option><option value='nise'>NISE / AWKA</option><option value='nkpor'>NKPOR</option><option value='nnewi_central_locations'>NNEWI-CENTRAL LOCATIONS</option><option value='ogidi'>OGIDI / AWKA</option><option value='onitsha'>ONITSHA</option><option value='onitsha_central_locations'>ONITSHA CENTRAL LOCATIONS</option><option value='umuokpe'>UMUOKPE / AWKA</option></select>";

var bauchi = "<span class='normalfontwhite'>Places in Bauchi</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='bauchi'>EVERYWHERE</option><option value='alkaleri'>ALKALERI</option><option value='bauchi_central_locations'>BAUCHI CENTRAL LOCATIONS</option></select>";

var bayelsa = "<span class='normalfontwhite'>Places in Bayelsa</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='bayelsa'>EVERYWHERE</option><option value='attoada'>ATTOADA</option><option value='amassoma'>AMASSOMA</option><option value='brass'>BRASS</option><option value='elele'>ELELE</option><option value='kiama'>KIAMA</option><option value='sagbama'>SAGBAMA</option><option value='wilberforce_island'>WILBERFORCE ISLAND</option><option value='yenagoa_central_locations'>YENAGOA CENTRAL LOCATIONS</option></select>";

var benue = "<span class='normalfontwhite'>Places in Benue</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='benue'>EVERYWHERE</option><option value='gboko'>GBOKO</option><option value='katsina_ala'>KATSINA-ALA</option><option value='makurdi_central_locations'>MAKURDI CENTRL LOCATIONS</option><option value='mkar'>mkar</option><option value='vandekya'>VANDEKYA</option><option value='yandev'>YANDEV</option></select>";

var borno = "<span class='normalfontwhite'>Places in Borno</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='borno'>EVERYWHERE</option><option value='auno'>AUNO</option><option value='maiduguri_central_locations'>MAIDIGURI-CENTRAL LOCATIONS</option></select>";

var cross_river = "<span class='normalfontwhite'>Places in Cross river</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='cross_river'>EVERYWHERE</option><option value='akampa'>AKAMPA</option><option value='calabar_central_locations'>CALABAR-CENTRAL LOCATIONS</option><option value='ikom'>IKOM</option><option value='ogoja'>OGOJA</option></select>";

var delta = "<span class='normalfontwhite'>Places in  Delta</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='delta'>EVERYWHERE</option><option value='abraka'>ABRAKA</option><option value='agbarho'>AGBARHO</option><option value='agbor'>AGBOR</option><option value='asaba_central_locations'>ASABA CENTRAL LOCATIONS</option><option value='isele_uku'>ISELE-UKU</option><option value='sapele_central_locations'>SAPELE_CENTRAL_LOCATIONS</option><option value='ughelli'>UGHELLI</option><option value='umunede'>UMUNEDE</option><option value='warri_central_locations'>WARRI CENTRAL LOCATIONS</option></select>";

var ebonyi = "<span class='normalfontwhite'>Places in Ebonyi</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='ebonyi'>EVERYWHERE</option><option value='abakaliki'>ABAKALIKI</option><option value='abakaliki_central_locations'>ABAKALIKI-CENTRAL LOCATIONS</option></select>";

var edo = "<span class='normalfontwhite'>Places in Edo</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='edo'>EVERYWHERE</option><option value='benin_city_central_locations'>BENIN CITY-CENTRAL LOCATIONS</option><option value='igeduma'>IGEDUMA</option><option value='auchi'>AUCHI</option><option value='okada'>OKADA</option></select>";

var ekiti = "<span class='normalfontwhite'>Places in Ekiti</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='ekiti'>EVERYWHERE</option><option value='ado_ekiti_central_locations'>ADO EKITI-CENTRAL LOCATIONS</option><option value='efon_ala_aye'>EFON ALA AYE</option><option value='ikogosi'>IKOGOSI</option><option value='ikole'>IKOLE</option><option value='ilupeju'>ILUPEJU</option><option value='ise_ekiti'>ISE-EKITI</option><option value='ode'>ODE</option><option value='omuo'>OMUO</option><option value='otun'>OTUN</option></select>";

var enugu = "<span class='normalfontwhite'>Places in Enugu</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='enugu'>EVERYWHERE</option><option value='agbani_town'>AGBANI TOWN</option><option value='aniri'>ANIRI</option><option value='enugu_central_locations'>ENUGU CENTRAL LOCATIONS</option><option value='ituku_ozalla'>ITUKU OZALLA</option><option value='nsukka_central_locations'>NSUKKA CENTRAL LOCATIONS</option></select>";

var gombe = "<span class='normalfontwhite'>Places in Gombe</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='gombe'>EVERYWHERE</option><option value='ashaka'>ASHAKA</option><option value='bajoga'>BAJOGA</option><option value='gombe'>GOMBE</option><option value='malamfidi'>MALAMFIDI</option></select>";

var imo = "<span class='normalfontwhite'>Places in Imo</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='imo'>EVERYWHERE</option><option value='ihiagwa'>IHIAGWA</option><option value='isuochi'>ISUOCHI</option><option value='nekede'>NEKEDE</option><option value='okigwe'>OKIGWE</option><option value='orlu'>ORLU</option><option value='owerri_central_locations'>OWERRI CENTRAL LOCATIONS</option></select>";

var jigawa = "<span class='normalfontwhite'>Places in Jigawa</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='jigawa'>EVERYWHERE</option><option value='dutse'>DUTSE</option><option value='gumel'>GUMEL</option><option value='hadeja'>HADEJA</option><option value='jahum'>JAHUM</option><option value='kazaure'>KAZAURE</option><option value='ringim'>RINGIM</option></select>";

var kaduna = "<span class='normalfontwhite'>Places in Kaduna</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='kaduna'>EVERYWHERE</option><option value='ikara'>IKARA</option><option value='jaji'>JAJI</option><option value='kaduna_central_locations'>KADUNA-CENTRAL LOCATIONS</option><option value='kafanchan'>KAFACHAN</option><option value='makarfi'>MAKARFI</option><option value='saye'>SAYE</option><option value='shika'>SHIKA</option><option value='zaria_central_locations'>ZARIA-CENTRAL LOCATIONS</option></select>";

var kano = "<span class='normalfontwhite'>Places in Kano</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='kano'>EVERYWHERE</option><option value='bichi'>BICHI</option><option value='gaya'>GAYA</option><option value='gezewa'>GEZEWA</option><option value='kachaka'>KACHAKA</option><option value='kankiya'>KANKIYA</option><option value='kano_central_locations'>KANO-CENTRAL LOCATIONS</option><option value='tawanau'>TAWANAU</option><option value='waje'>WAJE</option><option value='wudil'>WUDIL</option></select>";

var katsina = "<span class='normalfontwhite'>Places in Katsina</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='katsina'>EVERYWHERE</option><option value='batagawara'>BATAGAWARA</option><option value='daura'>DAURA</option><option value='dutsinma'>DUTSINMA</option><option value='funtua'>FUNTUA</option><option value='katsina_town_central_locations'>KATSINA TOWN-CENTRAL LOCATIONS</option><option value='mashi'>MASHI</option></select>";

var kebbi = "<span class='normalfontwhite'>Places in Kebbi</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='kebbi'>EVERYWHERE</option><option value='ambrusa'>AMBRUSA</option><option value='argungu'>ARGUNGU</option><option value='birnin_kebbi'>BIRNIN KEBBI</option></select>";

var kogi = "<span class='normalfontwhite'>Places in Kogi</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='kogi'>EVERYWHERE</option><option value='abobo'>ABOBO</option><option value='ajaokuta'>AJAOKUTA</option><option value='ankpa'>ANKPA</option><option value='ayangba'>AYANGBA</option><option value='idah'>IDAH</option><option value='itakpe'>ITAKPE</option><option value='lokoja_central_locations'>LOKOJA-CENTRAL LOCATIONS</option><option value='obajana'>OBAJANA</option><option value='okenne'>OKENNE</option></select>";

var kwara = "<span class='normalfontwhite'>Places in Kwara</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='kwara'>EVERYWHERE</option><option value='ilorin_central_locations'>ILORIN CENTRAL LOCATIONS</option><option value='offa'>OFFA</option></select>";

var nassarawa = "<span class='normalfontwhite'>Places in Nassarawa</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='nassarawa'>EVERYWHERE</option><option value='akwanga'>AKWANGA</option><option value='amaku'>AMAKU</option><option value='doma'>DOMA</option><option value='keffi'>KEFFI</option><option value='lafia'>LAFIA</option><option value='lafia_central_locations'>LAFIA-CENTRAL LOCATIONS</option><option value='masaka'>MASAKA</option><option value='nakere'>NAKERE</option><option value='new_karu'>NEW KARU</option><option value='wamba'>WAMBA</option></select>";

var niger = "<span class='normalfontwhite'>Places in Niger</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='niger'>EVERYWHERE</option><option value='agai'>AGAI</option><option value='baddegi'>BADDEGI</option><option value='bida'>BIDA</option><option value='kontagora'>KONTAGORA</option><option value='lapai'>LAPAI</option><option value='madala'>MADALA</option><option value='minna'>MINNA</option><option value='minna_central_locations'>MINNA-CENTRAL LOCATIONS</option><option value='suleja'>SULEJA</option><option value='zuba'>ZUBA</option></select>";

var ogun = "<span class='normalfontwhite'>Places in Ogun</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='Ogun'>EVERYWHERE</option><option value='abeokuta_central_locations'>ABEOKUTA-CENTRAL LOCATIONS</option><option value='agbara_industrial_estate'>AGBARA INDUSTRIAL ESTATE</option><option value='ago_iwoye'>AGO_IWOYE</option><option value='ajegunle'>AJEGUNLE</option><option value='akute'>AKUTE</option><option value='alagbado'>ALAGBADO</option><option value='awode_apa'>AWODE APA</option><option value='ewekoro_wampco'>EWEKORO / WAPCO</option><option value='ijebu_ife'>IJEBU IFE</option><option value='ijebu_igbo'>IJEBU IGBO</option><option value='ijebu_ode_central_locations'>IJEBU ODE-CENTRAL LOCATIONS</option><option value='imagbon'>IMAGBON</option><option value='itele'>ITELE</option><option value='iwuopin'>IWUOPIN</option><option value='mosimi_wapco'>MOSIMI / WAPCO</option><option value='ogijo'>ogijo</option><option value='oru'>ORU</option><option value='otta_town'>OTTA TOWN</option><option value='sango_otta'>SANGO OTTA</option><option value='wasimi'>WASIMI</option></select>";

var ondo = "<span class='normalfontwhite'>Places in Ondo</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='ondo'>EVERYWHERE</option><option value='akure'>AKURE</option><option value='akure_central_locations'>AKURE-CENTRAL LOCATIONS</option><option value='igbokoda'>IGBOKODA</option><option value='ondo_town'>ONDO TOWN</option><option value='ore'>ORE</option><option value='owena'>OWENA</option></select>";

var osun = "<span class='normalfontwhite'>Places in Osun</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='osun'>EVERYWHERE</option><option value='ada'>ADA</option><option value='ede'>EDE</option><option value='ife'>IFE</option><option value='igbajo'>IGBAJO</option><option value='ikire'>IKIRE</option><option value='ila_orangun'>ILA ORANGUN</option><option value='ile_ife_central_locations'>ILE IFE-CENTRAL LOCATIONS</option><option value='ilesha'>ILESHA</option><option value='iloko'>ILOKO</option><option value='iree'>IREE</option><option value='oshogbo_central_locations'>OSHOGBO-CENTRAL LOCATIONS</option><option value='osogbo'>OSOGBO</option></select>";

var oyo = "<span class='normalfontwhite'>Places in Oyo</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='oyo'>EVERYWHERE</option><option value='egbeda'>EGBEDA</option><option value='ibadan'>IBADAN</option><option value='ibadan_central_locations'>IBADAN-CENTRAL LOCATIONS</option><option value='iseyin'>ISEYIN</option><option value='iwo'>IWO</option><option value='lalupon'>LALUPON</option><option value='ogbomoso'>OGBOMOSO</option><option value='oyo_town'>OYO TOWN</option></select>";

var plateau = "<span class='normalfontwhite'>Places in Plateau</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='plateau'>EVERYWHERE</option><option value='barikin_ladi'>BARIKIN LADI</option><option value='haipang'>HAIPANG</option><option value='jos'>JOS</option><option value='jos_central_locations'>JOS-CENTRAL LOCATIONS</option><option value='kuru'>KURU</option><option value='kuru_janter'>KURU JANTER</option><option value='riyom'>RIYOM</option><option value='vom'>VOM</option><option value='zawan'>ZAWAN</option></select>";

var rivers = "<span class='normalfontwhite'>Places in rivers</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='rivers'>EVERYWHERE</option><option value='abhonema'>ABHONEMA</option><option value='airport_road_port_harcourt'>AIRPORT ROAD-PORT HARCOURT</option><option value='aluu'>ALUU</option><option value='bonny_island_central_locations'>BONNY ISLAND-CENTRAL LOCATIONS</option><option value='bori'>BORI</option><option value='elimbu'>ELIMBU</option><option value='emouha'>EMOUHA</option><option value='eneka'>ENEKA</option><option value='etche'>ETCHE</option><option value='gokana'>GOKANA</option><option value='igwuruta'>IGWURUTA</option><option value='isiokpo'>ISIOKPO</option></select>";

var sokoto = "<span class='normalfontwhite'>Places in Sokoto</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='sokoto'>EVERYWHERE</option><option value='sokoto_town_central_locations'>SOKOTO TOWN-CENTRAL LOCATIONS</option><option value='sokoto_gusau'>SOKOTO_GUSAU</option></select>";

var taraba = "<span class='normalfontwhite'>Places in Taraba</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='taraba'>EVERYWHERE</option><option value='jalingo'>JALINGO</option><option value='lankaviri'>LANKAVIRI</option><option value='zing'>ZING</option></select>";

var yobe = "<span class='normalfontwhite'>Places in Yobe</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='yobe'>EVERYWHERE</option><option value='damaturu'>DAMATURU</option><option value='gakigana'>GAKIGANA</option><option value='potiskum'>POTISKUM</option></select>";

var zamfara = "<span class='normalfontwhite'>Places in zamfara</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='zamfara'>EVERYWHERE</option><option value='gusau'>GUSAU</option><option value='talata_mafara'>TALATA MAFARA</option></select>";

var lagos = "<span class='normalfontwhite'>Places in Lagos</span> <br/><select id='placefield' name='placefield' style='width:130px' class='field'><option value='ajah'>Ajah</option><option value='agbede'>Agbede</option><option value='agege'>Agege</option><option value='aguda'>Aguda</option><option value='apapa'>Apapa</option><option value='ajah'>Ajah</option><option value='badagry'>Badagry</option><option value='eko'>Eko</option><option value='epe'>Epe</option><option value='ikeja'>Ikeja</option><option value='ikorodu'>Ikorodu</option><option value='isolo'>Isolo</option><option value='jibowu'>Jibowu</option><option value='lekki'>Lekki</option><option value='moroko'>Maroko</option><option value='maryland'>Maryland</option><option value='mushin'>Mushin</option><option value='obalende'>Obalende</option><option value='obanikoro'>Obanikoro</option><option value='ojota'>Ojota</option><option value='oshodi'>Oshodi</option><option value='shangotedo'>Shangotedo</option><option value='shogunle'>Shogunle</option><option value='surulere'>Surulere</option><option value='tinubu'>Tinubu</option><option value='others'>Other places</option></select>";
